"""empty message

Revision ID: 0b4baba6ff89
Revises: 34e4de2f7d15
Create Date: 2017-07-13 15:38:46.027000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b4baba6ff89'
down_revision = '34e4de2f7d15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('created_date', sa.DateTime(), server_default=sa.func.current_timestamp()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'created_date')
    # ### end Alembic commands ###
