"""empty message

Revision ID: 1e504e9d8558
Revises: 0b4baba6ff89
Create Date: 2017-07-13 16:28:51.150000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e504e9d8558'
down_revision = '0b4baba6ff89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('author', sa.String(length=10), nullable=True))
    op.create_unique_constraint(None, 'articles', ['author'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='unique')
    op.drop_column('articles', 'author')
    # ### end Alembic commands ###
