"""empty message

Revision ID: 938a2585922a
Revises: 1e504e9d8558
Create Date: 2017-07-14 16:21:02.304000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '938a2585922a'
down_revision = '1e504e9d8558'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_column(u'user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'user', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_table('role')
    # ### end Alembic commands ###
