"""empty message

Revision ID: 973479a321b7
Revises: a32b9dece065
Create Date: 2017-07-18 20:06:55.419000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '973479a321b7'
down_revision = 'a32b9dece065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'articles', ['author'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='unique')
    # ### end Alembic commands ###
