"""empty message

Revision ID: a32b9dece065
Revises: e4090d29d2a2
Create Date: 2017-07-18 19:57:47.518000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a32b9dece065'
down_revision = 'e4090d29d2a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'articles_author_key', 'articles', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'articles_author_key', 'articles', ['author'])
    # ### end Alembic commands ###
